services:
  #API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boutique_palansaeg_api
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  #Base de datos
  postgres:
    image: postgres:15-alpine
    container_name: boutique_palansaeg_postgesql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
